extends:
  - airbnb-base
  - airbnb-typescript/base

parserOptions:
  project: ./tsconfig.json

rules:
  import/prefer-default-export: off
  no-case-declarations: off
  no-console: off
  arrow-body-style: off
  max-len:
    - error
    - code: 120
      ignoreComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreUrls: true
